package com.recipe.scrapping.Enum;

public enum CuisineCategory {
            Indian,
            South_Indian,
            Rajathani,
            Punjabi,
            Bengali,
            orissa,
            Gujarati,
            Maharashtrian,
            Andhra,
            Kerala,
            Goan,
            Kashmiri,
            Himachali,
            Tamil_nadu,
            Karnataka,
            Sindhi,
            Chhattisgarhi,
            Madhya_pradesh,
            Assamese,
            Manipuri,
            Tripuri,
            Sikkimese,
            Mizo,
            Arunachali,
            uttarakhand,
            Haryanvi,
            Awadhi,
            Bihari,
            Uttar_pradesh,
            Delhi,
            North_Indian,

    }
